# Generated by Django 2.2.6 on 2021-03-03 12:20

from django.db import migrations, models
import django.db.models.deletion
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210219_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='будьте вежливы. нас читают дети', validators=[posts.validators.validate_not_empty], verbose_name='Текст сообщения'),
        ),
    ]
