# Generated by Django 2.2.6 on 2021-04-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_avatar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='avatar',
            constraint=models.UniqueConstraint(fields=('image', 'profile'), name='uniq_avatar'),
        ),
    ]
